### PR TITLE
Add arm64 support

### PR DESCRIPTION
**Pull request by Dreamail**

### CODE REVIEW

**Comment by MoustacheOff** [comment]
This issue should be renamed in: Add support to custom OpenJDK builds.

**Comment by Dreamail** [comment]
> This issue should be renamed in: Add support to custom OpenJDK builds.

I am sorry that I forgot mojang didn't add support for arm64 natively.

**Comment by MoustacheOff** [comment]
> > This issue should be renamed in: Add support to custom OpenJDK builds.
> 
> I am sorry that I forgot mojang didn't add support for arm64 natively.

No problem ;)

**Comment by GameParrot** [comment]
Building universal since commit [f14748c](https://github.com/GameParrot/minecraft-mac-window-fix/commit/f14748c4519ecfb0b3856200d5d65442649cda9c)

**Pull request closed without merging**
